<%@ Page Title="" Language="C#" MasterPageFile="~/templates/Unapproved.Master" AutoEventWireup="true" CodeBehind="DeclareUnapprovedMajor.aspx.cs" Inherits="OSAG.profiles.DeclareUnapprovedMajor" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <br />
    <br />
    <div style="margin-right: auto; margin-left: auto; text-align: center">
        <h4>
            <asp:Label ID="lblHead" runat="server" Text="Add Major(s)"></asp:Label></h4>
        <asp:DropDownList ID="ddlMajors" runat="server"
            AutoPostBack="true"
            DataSourceID="sqlsrcMajors"
            DataTextField="MajorName"
            DataValueField="MajorID">
        </asp:DropDownList>
        <asp:Button ID="btnAddMajor" runat="server" Text="Add" OnClick="btnAddMajor_Click" />
        <br />
        <asp:Button ID="btnDoneMajors" runat="server" Text="Done" OnClick="btnDoneMajors_Click" />
        <br />
        <br />
        <h4>Current Majors/Minors</h4>
        <asp:GridView ID="grdvHasMajor" runat="server" DataSourceID="sqlsrcHasMajor"
            AutoGenerateColumns="false"
            AllowPaging="true"
            CellPadding="10"
            DataKeyNames="MajorID, StudentID, MemberID"
            HorizontalAlign="Center"
            ShowHeaderWhenEmpty="true"
            AutoGenerateDeleteButton="true">
            <Columns>
                <asp:BoundField ReadOnly="true" HeaderText="Major Name" DataField="MajorName" />
                <asp:BoundField ReadOnly="true" HeaderText="Is Minor" DataField="IsMinor" />
            </Columns>
        </asp:GridView>

        <asp:SqlDataSource ID="sqlsrcMajors" runat="server"
            ConnectionString="<%$ ConnectionStrings:OSAG %>"
            SelectCommand="SELECT * FROM Major WHERE IsMinorOnly IS NULL OR IsMinorOnly = 0 ORDER BY MajorName;"></asp:SqlDataSource>
        <asp:SqlDataSource ID="sqlsrcHasMajor" runat="server"
            ConnectionString="<%$ ConnectionStrings:OSAG %>"
            DeleteCommand="DELETE FROM HasMajor WHERE MajorID = @MajorID 
            AND ((StudentID = @StudentID AND MemberID IS NULL) 
            OR (MemberID = @MemberID AND StudentID IS NULL))"></asp:SqlDataSource>
    </div>
</asp:Content>
